development:
  adapter: postgresql
  encoding: unicode
  database: demo-1_development
  pool: 5
  username: demo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: demo-1_test
  pool: 5
  username: demo
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: demo-1_production
  pool: 5
  username: demo-1
  password:
